---
resources:
- name: concourse-docker-gradle-sample
  type: git
  source:
    uri: https://github.com/vernaillen/concourse-docker-gradle-sample.git

- name: docker-image
  type: docker-image
  source:
    repository: vernaillen/concourse-docker-gradle-sample

jobs:
- name: job-test-app
  public: true
  plan:
  - get: concourse-docker-gradle-sample
    trigger: true
  - task: web-app-tests
    file: concourse-docker-gradle-sample/ci/build.yml
  - put: docker-image
    params:
      build: concourse-docker-gradle-sample
