---
resources:
- name: concourse-docker-gradle-sample
  type: git
  source:
    uri: https://github.com/vernaillen/concourse-docker-gradle-sample.git

- name: docker-build
  type: docker-image
  source:
    repository: vernaillen/concourse-docker-gradle-sample

jobs:
- name: build-app
  public: true
  plan:
  - get: concourse-docker-gradle-sample
    trigger: true
  - task: gradle-build
    file: concourse-docker-gradle-sample/ci/build.yml
  - put: docker-build
    params:
      build: concourse-docker-gradle-sample/src/main/docker
